### ISSUE TITLE
Concating dfs pandas error

### ISSUE THREAD

**Issue by saycheeeeese** [biocore-ntnu/epic#55]
Hi 
 I have received the following error

```
Concating dfs. (File: run_epic, Log level: INFO, Time: Wed, 24 May 2017 14:50:32 )
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/epic", line 219, in <module>
    run_epic(args)
  File "/usr/local/lib/python2.7/dist-packages/bioepic-0.1.25-py2.7.egg/epic/run/run_epic.py", line 60, in run_epic
    df = pd.concat([df for df in dfs if not df.empty])
  File "/usr/local/lib/python2.7/dist-packages/pandas/tools/merge.py", line 845, in concat
    copy=copy)
  File "/usr/local/lib/python2.7/dist-packages/pandas/tools/merge.py", line 878, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate
```

I am unsure if this an error in pandas or epic? Any ideas of how to fix this?
Thanks

**Comment by endrebak** [comment]
Could you print the whole error message?

I think the problem ultimately comes from the fact that your custom chromosome files and bed files contain different chromosome names, so if you could send the output of 

`head <your_bed_files>` and `cat <your_chromsizes_file>` it would be appreciated.

So if your chromsizes file is called `build/lib/epic/scripts/chromsizes/dm3.chromsizes` you call `cat build/lib/epic/scripts/chromsizes/dm3.chromsizes` and print the output here. Same with the bed files you use please, only make sure to use head instead of cat.

**Comment by endrebak** [comment]
Epic might also not have found any enriched regions in your data, that is another possibility, but sounds unlikely to me. Could you print the whole command you use to invoke epic please?

Note to self: Add warning message if all dfs are empty before concating. Should go here: https://github.com/biocore-ntnu/epic/blob/master/epic/run/run_epic.py#L57 and matrix creation should still work afterwards.
